### ISSUE TITLE
BBCodes 2.0.2

### ISSUE THREAD

**Issue by KMPR8** [Teralios/de.teralios.bbcodes#1]
Hallo, 
ich habe mit den BBCodes einige Probleme, die ich mir nicht erklären kann, siehe
http://wbb-center.net/board/index.php/Thread/5048-BBCodes-2-0-2/?postID=35495#post35495

Beim Wechsel von WCF 2.0 auf WCF 2.1 habe ich die alten BBCodes nicht deinstalliert, weil ich von dieser Notwendigkeit nichts wusste!

Gibt es Rat von deiner Seite?

Danke schon mal im Voraus, KMP

**Comment by Teralios** [comment]
Ob man die BBCodes deinstalliert hat oder nicht, hat keine Auswirkung.

Zum erst genannten Problem: Das Problem liegt in dem Fall nicht an mir oder dir oder sonst jemand, sondern an PHP. Du hast vermutlich PHP5.3 oder 5.4 installierte und ich habe eine Funktion aus PHP 5.5 verwendet. Ich werde den Fehler heute noch beheben.

Zu dem zweiten Fehler kann ich so nichts sagen, da keine Farbanweisungen gebe und diese dem Stil obliegen. Darstellungsfehler liegen in dem Fall am Stil, nicht jedoch an den BBCodes und da kann ich auch nicht helfen.
