### ISSUE TITLE
BBCodes 2.0.3

### ISSUE THREAD

**Issue by KMPR8** [Teralios/de.teralios.bbcodes#2]
Hallo,
ich habe den Update installiert (wurde automatisch angeboten).

An dem Fehler bei Eingabe von [h1='sprungmarke',1]Headline[/h1] 
hat dies nichts geändert. (Cache wurde mehrfach geleert)

Bei den erzeugten Überschriften im Inhaltsverzeichnis wird H1 mit einem führenden ">" ausgegeben.
H2 wird in einer größeren Schrift, aber ohne ein führendes ">" ausgegeben. Das war in Version 2.02 nicht so.

Bei den im Inhaltsverzeichnis übergebenen Links hinter den Überschriften fehlt das Fragezeichen vor "postID", sodass man bei Klick auf den Verzeichniseintrag nicht bei der Sprungmarke, sondern auf der Startseite des Forums landet. Ergänzt man hier in der URL-Zeile das Fragezeichen an der entspr. Position, landet man an der korrekten Position des Beitrags.

Hier wäre für mich noch interessant zu wissen, ob bzw. wie man die Positionierung der Sprungmarke beeinflussen kann. Da ich einen fixierten Header benutze, steht die "angesprungene" Überschrift hinter dem Kopfmenü.

Grüße, KMPR8

**Comment by Teralios** [comment]
Keiner der Fehler ist in dieser Form nach zu vollziehen und wird auch leider von keinem anderen in der Form gemeldet.

Ohne einen entsprechenden Link kann ich diese Fehler also auch nicht nachvollziehen, es tut mir leid.

Die Positionierung der Sprungmarken kann man auch nicht beeinflussen, da der Browser automatisch selbst zu den passenden stellen springt. Wenn dann müsste man das Verhalten des Browser ändern, darauf habe ich keinen Einfluss!
