### ISSUE TITLE
HTTP 500 in Blog 2.1

### ISSUE THREAD

**Issue by GreXXL** [Teralios/de.teralios.bbcodes#3]
Wenn man das Blog Paket installiert, bekomme ich auf bestimmten Seiten im Blog 2.1 einen HTTP 500 anstatt einer vernünftigen Seite. Deinstalliert man die Blog-Integration wird der Beitrag richtig dargestellt.

Link: http://www.grexxl.com/entry/14-was-ist-die-richtige-hosting-f%C3%BCr-mein-projekt/ oder http://www.grexxl.com/entry/9-die-besten-ressourcen-zu-woltlab-produkten/

Warum ist mir nicht klar, es wird nur "pclist" als BBCode verwendet. In anderen Artikeln die den BBCode einsetzen funktioniert alles korrekt.

**Comment by Teralios** [comment]
Ich hab den Fehler schon lokalisiert, ich muss nur noch das Update-Package packen.
